"""Send the generated daily brief to Telegram."""

from __future__ import annotations

import os
from pathlib import Path
import mimetypes

import requests
import urllib3


TELEGRAM_API_BASE = "https://api.telegram.org/bot{token}/{method}"
MAX_CAPTION_LENGTH = 1024
MAX_TELEGRAM_MESSAGE_LENGTH = 3900


class TelegramConfigError(RuntimeError):
    """Raised when Telegram delivery is requested but not configured."""


def load_env_file(path: str = ".env") -> None:
    """Load simple KEY=VALUE pairs from a local .env file if it exists."""
    env_path = Path(path)
    if not env_path.exists():
        return

    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


def send_brief_to_telegram(
    brief_path: Path,
    *,
    token: str | None = None,
    chat_id: str | None = None,
) -> None:
    load_env_file()

    bot_token = token or os.getenv("TELEGRAM_BOT_TOKEN")
    target_chat_id = chat_id or os.getenv("TELEGRAM_CHAT_ID")

    if not bot_token or not target_chat_id:
        raise TelegramConfigError(
            "Set TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID to enable Telegram delivery."
        )

    if not brief_path.exists():
        raise FileNotFoundError(f"Brief file not found: {brief_path}")

    caption = build_caption(brief_path)
    url = TELEGRAM_API_BASE.format(token=bot_token, method="sendDocument")

    with brief_path.open("rb") as brief_file:
        response = telegram_post(
            url,
            data={
                "chat_id": target_chat_id,
                "caption": caption,
            },
            files={
                "document": (
                    brief_path.name,
                    brief_file,
                    mimetypes.guess_type(brief_path.name)[0] or "application/octet-stream",
                )
            },
        )

    if is_network_block_response(response):
        send_brief_as_messages(brief_path, bot_token, target_chat_id)
        return

    response.raise_for_status()
    payload = response.json()
    if not payload.get("ok"):
        description = payload.get("description", "Telegram API returned ok=false")
        raise RuntimeError(description)


def send_brief_as_messages(brief_path: Path, bot_token: str, chat_id: str) -> None:
    text = brief_path.read_text(encoding="utf-8")
    chunks = split_message(text)
    url = TELEGRAM_API_BASE.format(token=bot_token, method="sendMessage")

    for index, chunk in enumerate(chunks, start=1):
        prefix = f"Daily brief part {index}/{len(chunks)}\n\n"
        response = telegram_post(
            url,
            data={
                "chat_id": chat_id,
                "text": prefix + chunk,
                "disable_web_page_preview": "true",
            },
        )

        if is_network_block_response(response):
            raise RuntimeError(
                "Telegram API appears to be blocked on this network. "
                "Switch to a network/VPN that allows api.telegram.org and retry."
            )

        response.raise_for_status()
        payload = response.json()
        if not payload.get("ok"):
            description = payload.get("description", "Telegram API returned ok=false")
            raise RuntimeError(description)


def telegram_post(url: str, **kwargs: object) -> requests.Response:
    try:
        return requests.post(
            url,
            timeout=30,
            verify=should_verify_ssl(),
            allow_redirects=False,
            **kwargs,
        )
    except requests.RequestException as exc:
        raise RuntimeError(
            "Telegram delivery failed. If this happened on local Wi-Fi, try a hotspot "
            "or VPN that allows api.telegram.org."
        ) from exc


def split_message(text: str) -> list[str]:
    chunks = []
    remaining = text

    while len(remaining) > MAX_TELEGRAM_MESSAGE_LENGTH:
        split_at = remaining.rfind("\n## ", 0, MAX_TELEGRAM_MESSAGE_LENGTH)
        if split_at <= 0:
            split_at = remaining.rfind("\n", 0, MAX_TELEGRAM_MESSAGE_LENGTH)
        if split_at <= 0:
            split_at = MAX_TELEGRAM_MESSAGE_LENGTH

        chunks.append(remaining[:split_at].strip())
        remaining = remaining[split_at:].strip()

    if remaining:
        chunks.append(remaining)

    return chunks


def build_caption(brief_path: Path) -> str:
    title = "Daily Intelligence Brief"
    first_line = brief_path.read_text(encoding="utf-8").splitlines()[0].lstrip("# ")
    if first_line:
        title = first_line

    caption = f"{title}\nGenerated by Simran Intelligence OS."
    return caption[:MAX_CAPTION_LENGTH]


def should_verify_ssl() -> bool:
    value = os.getenv("TELEGRAM_VERIFY_SSL", "true").strip().lower()
    verify = value not in {"0", "false", "no", "off"}
    if not verify:
        urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
    return verify


def is_network_block_response(response: requests.Response) -> bool:
    url = response.url.lower()
    location = response.headers.get("Location", "").lower()
    return (
        "172.16.16.16" in url
        or "/block/webcat" in url
        or "172.16.16.16" in location
        or "/block/webcat" in location
    )
